modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
[[mods]]
modId="umbral_skies"
version="${file.jarVersion}"
displayName="Umbral Skies" #mandatory
# updateJSONURL="https://change.me.example.invalid/updates.json"
# displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
# logoFile="examplemod.png"
# credits=""
authors="Drullkus"
# displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
description='''
Find Twilight Forest features in The Aether!
'''
[[dependencies.umbral_skies]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.umbral_skies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.umbral_skies]]
    modId="twilightforest"
    mandatory=true
    versionRange="[4.2.1614,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.umbral_skies]]
    modId="aether"
    mandatory=true
    versionRange="[0.4.0,)"
    ordering="NONE"
    side="BOTH"